### ISSUE TITLE
Faltan capturas de pantalla

### ISSUE THREAD

**Issue by LuisJoseSanchez** [PGRtechDeveloper/Prision#1]
La aplicación está bien pero debe haber una carpeta con capturas de pantalla que ilustren su funcionamiento sin tener que cargar la base de datos, crear el proyecto, etc.

**Comment by PGRtechDeveloper** [comment]
Gracias por el aviso. Creía que las había subido junto con el proyecto y se me debió pasar. Ya sí están. Un saludo
